# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# CentOS 7.7.1908 installed with the following libraries:
#  - Bazel 4.0.0
#  - Clang 11.1.0
#  - libstdc++8 or greater
#  - openjdk-8

FROM centos:centos7.7.1908 as base

RUN curl https://copr.fedorainfracloud.org/coprs/vbatts/bazel/repo/epel-7/vbatts-bazel-epel-7.repo > /etc/yum.repos.d/vbatts-bazel-epel-7.repo && \
    echo "source /opt/rh/devtoolset-8/enable" >> ~/.bashrc

RUN yum update -y && yum install -y bazel4 centos-release-scl epel-release wget gcc git

RUN yum update -y && yum install -y cmake3 devtoolset-8

RUN wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/llvm-project-11.1.0.src.tar.xz && tar xvf llvm-project-11.1.0.src.tar.xz

RUN mkdir /llvm-project-11.1.0.src/build && \
    cd /llvm-project-11.1.0.src/build && \
    source ~/.bashrc && \
    cmake3 -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS=clang -G "Unix Makefiles" ../llvm && \
    make && \
    make install -j 8 && \
    rm -rf /llvm-project-11.1.0.src

RUN git clone --depth 1 https://github.com/flink-extended/clink.git /tmp/clink && \
    cd /tmp/clink && \
    git submodule update --init --recursive && \
    bazel build --disk_cache=~/.cache/bazel @tf_runtime//tools:bef_executor_lite && \
    bazel build --disk_cache=~/.cache/bazel @tf_runtime//tools:tfrt_translate && \
    rm -rf /tmp/clink
