# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Ubuntu 16.04 installed with the following libraries:
#  - Bazel 4.0.0
#  - Clang 11.1.0
#  - libstdc++8 or greater
#  - openjdk-8

FROM ubuntu:16.04 as base

RUN apt-get update && apt-get install -y apt-transport-https software-properties-common sudo

RUN echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main" >> /etc/apt/sources.list && \
    echo "deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial main" >> /etc/apt/sources.list && \
    echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-11 main" >> /etc/apt/sources.list && \
    echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" >> /etc/apt/sources.list.d/bazel.list

RUN add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
    apt-get update && \
    apt-get install -y --allow-unauthenticated --fix-missing bazel clang-11 gcc-8 g++-8 openjdk-8-jdk git && \
    rm -rf /var/lib/apt/lists/* 

RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-11 11 && \
    update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-11 11

RUN git clone --depth 1 https://github.com/flink-extended/clink.git /tmp/clink && \
    cd /tmp/clink && \
    git submodule update --init --recursive && \
    bazel build --disk_cache=~/.cache/bazel @tf_runtime//tools:bef_executor_lite && \
    bazel build --disk_cache=~/.cache/bazel @tf_runtime//tools:tfrt_translate && \
    rm -rf /tmp/clink
